### ISSUE TITLE
Adicionar pacotes essenciais

### ISSUE THREAD

**Issue by afmireski** [afmireski/password-vault#1]
# Description
Nessa Issue devem ser adicionados os pacotes essenciais da `stack` do `projeto`. Ou seja pacotes que adicionem suporte ao `graphql` e ao `prisma`.

```zsh
yarn add prisma -D

yarn add @nestjs/graphql @nestjs/apollo graphql apollo-server-express 

yarn add @paljs/plugins prisma-nestjs-graphql
```

# Tasks
- [x] Adicionar pacotes do prisma;
- [x] Adicionar pacotes do graphql;
- [x] Adicionar pacotes auxiliares;
- [x] Configurar o prisma;
- [x] Configurar o graphql;
- [x] Atualizar CHANGELOG.md;
