### ISSUE TITLE
Implementar funcionalidades referentes a tabela de categorias

### ISSUE THREAD

**Issue by afmireski** [afmireski/password-vault#11]
# Description
As `Categorias` são um agrupamento de senhas que seguem algum critério pré-definido pelo usuário. Todo usuário pode ter 0 ou mais categorias, com o nome que desejar.

O usuário pode atualizar o nome de uma categoria a qualquer momento, porém, caso ele queira exclui-lá, todas as suas senhas contidas nela serão perdidas.

## CreateCategory
É informado o `nome` da categoria e a qual usuário ela pertencerá.
```typescript
interface Input {
	user_id: string;
	name: string;
}
```

## FindCategory
Busca uma categoria pelo seu id. Caso não a encontre retorna uma exceção.
```typescript
interface Input {
	user_id: string;
}
```

## FindManyCategories
Busca todas as categorias pertencentes a um determinado usuário, aplicando os filtros desejados, ordenação e paginação. Caso nada de adicional seja informado, retorna todas as categorias daquele usuário seguindo a paginação padrão.
```typescript
interface Input {
	user_id: string;
	where?: CategoryWhereInput;
	orderBy?: CategoryOrderByWithRelationInput
	pagination?: Pagination
}
```

## UpdateCategory
Permite a um usuário atualizar o nome de uma categoria específica. É necessário primeiro verificar se a categoria existe.
```typescript
interface Input {
	user_id: string;
	name: string;
}
```

## DeleteCategory
Permite a um usuário excluir uma de suas categorias. Por consequência, todas as senhas ali são excluídas também. É necessário primeiro verificar se a categoria existe.
```typescript
interface Input {
	user_id: string;
}
```

# Tasks
- [ ] Implementar DTOs necessários
- [ ] Implementar métodos:
	- [ ] CreateCategory
	- [ ] FindCategory
	- [ ] FindManyCategories
	- [ ] UpdateCategory
	- [ ] DeleteCategory
- [ ] Implementar end-points no resolver.
- [ ] Atualizar CHANGELOG.md
