### ISSUE TITLE
Implementar funcionalidades referentes a tabela de senhas

### ISSUE THREAD

**Issue by afmireski** [afmireski/password-vault#13]
# Description
A tabela de `senhas` necessita de algumas alterações para que o projeto fique mais parecido com um gerenciador de senhas. O título pode tornar-se uma variável opcional e mais um campo, `username` por exemplo, pode ser adicionado.
Geralmente gerenciadores de senha salvam além da senha um `username` que pode ser um `email` ou um `nick`.

Toda senha pertence a um usuário e opcionalmente a uma categoria. Caso um dos dois seja excluído as senhas relacionadas são apagadas também.

O valor da `senha` e o `username` devem ser encriptados na hora do armazenamento e decriptados por um método específico. Pode-se utilizar a biblioteca `crypto`.

O campo de `descrição` já pode servir de `título`, então esse último pode ser removido.

## CreatePassword
É informado o `valor` da `senha` e a qual usuário ela pertencerá. Opcionalmente podem ser recebidos o `username`, a `categoria`, um `título` e uma `descrição`.
```typescript
interface Input {
	user_id: string;
	value: string;
	username?: string;
	category_id?: string;
	description?: string;
}
```

## FindPassword
Busca uma única senha pelo seu id em conjunto com o id do usuário, para garantir que quem está requisitando é o dono da senha. Caso não a encontre retorna uma exceção.
```typescript
interface Input {
	password_id: string;
	user_id: string;
}
```

## FindManyPasswords
Busca todas as senhas pertencentes a um determinado usuário, aplicando os filtros desejados, ordenação e paginação. Caso nada de adicional seja informado, retorna todas as senhas daquele usuário seguindo a paginação padrão.
```typescript
interface Input {
	user_id: string;
	where?: PasswordWhereInput;
	orderBy?: PasswordOrderByWithRelationInput
	pagination?: Pagination
}
```

## UpdatePassword
Permite a um usuário atualizar o `valor`, o `username`, a `categoria` e a `descrição` de uma senha. É necessário primeiro verificar se a senha existe e pertence ao usuário informado.
```typescript
interface Input {
	user_id: string;
	value?: string;
	username?: string;
	category_id?: string;
	description?: string;
}
```

## DeletePassword
Permite a um usuário excluir uma de suas senhas, desde que senha mesmo sua. Como é um `hard delete` todas as senhas contidas ali são excluídas também.
```typescript
interface Input {
	password_id: string;
	user_id: string;
}
```

## DecryptPassword
Permite descriptografar as informações do `username` e do `value` da `senha`, revelando seu conteúdo.
```typescript
interface Input {
	password_id: string;
	user_id: string;
}
```

# Tasks
- [x] Realizar migração.
- [x] Implementar DTOs necessários
- [ ] Implementar métodos:
	- [ ] CreateCategory
	- [ ] FindCategory
	- [ ] FindManyCategories
	- [ ] UpdateCategory
	- [ ] DeleteCategory
	- [ ] DecryptPassword
- [ ] Implementar end-points no resolver.
- [ ] Atualizar CHANGELOG.md
