### ISSUE TITLE
Criar end-points para gerenciar a tabela de User

### ISSUE THREAD

**Issue by afmireski** [afmireski/password-vault#9]
# Description
## CreateUser
Recebe como `input`: o `email`, o `name` e a `password` do novo usuário. Verifica as entradas usando `class-validator`, encripta a senha usando a biblioteca `bcrypt` e salva o usuário no banco.
Retorna os dados seguindo a seleção do GraphQL.

## FindUser
Recebe como `input`: o `user_id`. Verifica as entradas usando `class-validator`, busca o usuário no banco pelo id e caso o encontre retorna. Caso não encontre retorna uma exceção. 
- Usuários excluídos não são retornados.
Retorna os dados seguindo a seleção do GraphQL.

## UpdateUser
Recebe como `input`: o `user_id` e opcionalmente o `email` e o `nome`. Verifica as entradas usando `class-validator` e caso esteja tudo certo tenta atualizar o usuário passando as novas informações. Em caso de falha lança exceção.
Retorna os dados seguindo a seleção do GraphQL.

## DeleteUser
Recebe como `input`: o `user_id`. Verifica as entradas usando `class-validator` e caso esteja tudo certo tenta realizar um `soft-delete` . Caso algo dê errado lança exceção.
- Usuários excluídos não são retornados.
Retorna os dados seguindo a seleção do GraphQL.

# Tasks
- [x] Instalar pacote `bcrypt`;
- [x] Criar resource de `users`;
- [x] Habilitar previews do prisma: `extendedWhereUnique` e `clientExtensions`;
- [x] Implementar `DTOs` necessários;
- [x] Implementar métodos no service:
  - [x] `CreateUser`;
  - [x] `FindUser`;
  - [x] `UpdateUser`;
  - [x] `DeleteUser`;
- [x] Implementar chamadas nos resolver;
- [x] Atualizar CHANGELOG.md
